package malls

import (
	"log"
	"net/url"
	"time"

	"github.com/lessbutter/alloff-api/config/ioc"
	"github.com/lessbutter/alloff-api/internal/core/domain"
	"go.mongodb.org/mongo-driver/mongo"
)

const MODULE_NAME = "flannels"

func AddFlannels() {
	// productTypes := map[string][]domain.AlloffProductType{
	// 	"Mens":          {domain.Male},
	// 	"Womens":        {domain.Female},
	// 	"Boys":          {domain.Boy},
	// 	"Girls":         {domain.Girl},
	// 	"Unisex Kids":   {domain.Boy, domain.Girl},
	// 	"Unisex Adults": {domain.Male, domain.Female},
	// }

	// brandProducTypes := map[string][]string{
	// 	"alexander-mcqueen":         {"Womens", "Mens"},
	// 	"apc":                       {"Mens"},
	// 	"balenciaga":                {"Womens", "Mens"},
	// 	"balmain":                   {"Womens", "Mens", "Unisex Kids"},
	// 	"bash":                      {""},
	// 	"burberry":                  {"Womens", "Mens", "Boys", "Girls"},
	// 	"barbour-international":     {"Womens", "Mens", "Boys", "Girls", "Unisex Kids"},
	// 	"barbour":                   {"Womens", "Mens", "Boys", "Girls", "Unisex Kids", "Unisex Adults"},
	// 	"coach":                     {"Womens"},
	// 	"champion":                  {""},
	// 	"calvin-klein-underwear":    {"Womens", "Mens"},
	// 	"calvin-klein-performance":  {"Womens", "Mens"},
	// 	"calvin-klein-jeans":        {"Boys", "Girls", "Unisex Kids"},
	// 	"canada-goose":              {"Womens", "Mens", "Boys", "Girls"},
	// 	"casablanca":                {"Womens", "Mens"},
	// 	"comme-des-garcons-play":    {"Womens", "Mens"},
	// 	"cp-company":                {"Mens"},
	// 	"chloe":                     {"Girls"},
	// 	"emporio-armani":            {"Womens", "Mens", "Boys", "Unisex Kids"},
	// 	"fred-perry":                {"Boys", "Mens"},
	// 	"fendi":                     {"Girls", "Boys"},
	// 	"ganni":                     {""},
	// 	"givenchy":                  {"Boys"},
	// 	"golden-goose-deluxe-brand": {"Womens", "Mens", "Unisex Adults"},
	// 	"isabel-marant-etoile":      {""},
	// 	"james-perse":               {""},
	// 	"jimmy-choo":                {"Womens"},
	// 	"jacquemus":                 {"Womens", "Mens"},
	// 	"jw-anderson":               {"Womens", "Mens", "Unisex Adults"},
	// 	"kenzo":                     {"Womens", "Mens", "Girls", "Boys"},
	// 	"lacoste":                   {"Boys", "Mens"},
	// 	"lauren-by-ralph-lauren":    {"Womens"},
	// 	"loewe":                     {"Womens", "Mens"},
	// 	"marcelo-burlon":            {"Womens", "Mens"},
	// 	"marni":                     {"Womens", "Mens"},
	// 	"max-mara":                  {"Womens"},
	// 	"max-mara-studio":           {"Womens"},
	// 	"max-mara-weekend":          {"Womens"},
	// 	"miu-miu":                   {"Womens"},
	// 	"moschino":                  {"Womens", "Mens", "Boys", "Girls", "Unisex Kids"},
	// 	"moncler":                   {"Womens", "Mens"},
	// 	"moose-knuckles":            {"Womens", "Mens"},
	// 	"off-white":                 {"Womens", "Mens", "Unisex Kids"},
	// 	"polo-ralph-lauren":         {"Womens", "Mens", "Boys", "Girls"},
	// 	"palm-angels":               {"Womens", "Mens", "Boys", "Girls", "Unisex Adults"},
	// 	"prada":                     {"Womens", "Mens"},
	// 	"rick-owens-drkshdw":        {"Womens", "Mens"},
	// 	"stone-island":              {"Boys", "Mens"},
	// 	"stella-mccartney":          {"Womens", "Boys", "Girls"},
	// 	"sportmax":                  {"Womens"},
	// 	"sporty-and-rich":           {"Womens"},
	// 	"thom-browne":               {"Womens", "Mens"},
	// 	"tommy-hilfiger":            {"Womens", "Mens"},
	// 	"tory-burch":                {"Womens"},
	// 	"ten-c":                     {"Mens"},
	// 	"under-armour":              {"Womens", "Mens"},
	// 	"ugg":                       {"Womens", "Mens", "Boys", "Girls", "Unisex Kids"},
	// 	"valentino":                 {"Womens", "Mens"},
	// 	"vivienne-westwood":         {"Womens", "Mens"},
	// }

	brands := map[string]domain.BrandDAO{
		"alexander-mcqueen": {
			KorName:               "알렉산더 맥퀸",
			EngName:               "Alexander McQueen",
			KeyName:               "ALEXANDERMCQUEEN",
			Description:           "컨템포러리",
			LogoImgUrl:            "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/ALEXANDERMCQUEEN.png",
			BackImgUrl:            "",
			SizeGuide:             []domain.SizeGuideDAO{},
			Created:               time.Now(),
			Onpopular:             false,
			MaxDiscountRate:       0,
			IsOpen:                false,
			IsHide:                false,
			InMaintenance:         false,
			NumNewProductsIn3days: 0,
			UseAlloffCategory:     false,
		},
		"apc": {
			KorName:       "아페쎄",
			EngName:       "A.P.C",
			KeyName:       "APC",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/APC.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide: []domain.SizeGuideDAO{
				{Label: "상의", ImgUrl: "https://alloff.s3.ap-northeast-2.amazonaws.com/sizeguides/A.P.C_TOP.png"},
				{Label: "하의", ImgUrl: "https://alloff.s3.ap-northeast-2.amazonaws.com/sizeguides/A.P.C_BOTTOM.png"},
				{Label: "슈즈", ImgUrl: "https://alloff.s3.ap-northeast-2.amazonaws.com/sizeguides/A.P.C_SHOES.png"},
			},
		},
		"balenciaga": {
			KorName:       "발렌시아가",
			EngName:       "Balenciaga",
			KeyName:       "BALENCIAGA",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/BALENCIAGA.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
		},
		"balmain": {
			KorName:       "발망",
			EngName:       "Balmain",
			KeyName:       "BALMAIN",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/BALMAIN.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
		},
		"bash": {
			KorName:       "바앤쉬",
			EngName:       "ba&sh",
			KeyName:       "BASH",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/BASH.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
		},
		"burberry": {
			KorName:       "버버리",
			EngName:       "BURBERRY",
			KeyName:       "BURBERRY",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/BURBERRY.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
		},
		"barbour-international": {
			KorName:       "바버 인터네셔널",
			EngName:       "Barbour International",
			KeyName:       "BARBOUR_INTERNATIONAL",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/BARBOUR_INTERNATIONAL.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
		},
		"barbour": {
			KorName:       "바버",
			EngName:       "Barbour",
			KeyName:       "BARBOUR",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/BARBOUR.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
		},
		"coach": {
			KorName:       "코치",
			EngName:       "Coach",
			KeyName:       "COACH",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/COACH.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
		},
		"champion": {
			KorName:       "챔피온",
			EngName:       "CHAMPION",
			KeyName:       "CHAMPION",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/CHAMPION.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
		},
		"calvin-klein-underwear": {
			KorName:       "캘빈클라인 언더웨어",
			EngName:       "CALVIN KLEIN UNDERWEAR",
			KeyName:       "CKUNDERWEAR",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/CKUNDERWEAR.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"calvin-klein-performance": {
			KorName:       "캘빈클라인 퍼포먼스",
			EngName:       "CALVIN KLEIN PERFORMANCE",
			KeyName:       "CKPERFORMANCE",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/CKPERFORMANCE.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"calvin-klein-jeans": {
			KorName:       "캘빈클라인 진",
			EngName:       "CALVIN KLEIN JEANS",
			KeyName:       "CKJEANS",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/CKJEANS.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"canada-goose": {
			KorName:       "캐나다 구스",
			EngName:       "CANADA GOOsE",
			KeyName:       "CANADAGOOSE",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/CANADAGOOSE.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"casablanca": {
			KorName:       "캐나다 구스",
			EngName:       "CASABLANCA",
			KeyName:       "CASABLANCA",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/CASABLANCA.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"comme-des-garcons-play": {
			KorName:       "꼼데가르송 플레이",
			EngName:       "COMME DES GARCONS PLAY",
			KeyName:       "COMME_DES_GARCONS_PLAY",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/COMME_DES_GARCONS_PLAY.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"cp-company": {
			KorName:       "CP컴퍼니",
			EngName:       "CP company",
			KeyName:       "CPCOMPANY",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/CPCOMPANY.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"chloe": {
			KorName:       "끌로에",
			EngName:       "Chloé",
			KeyName:       "CHLOE",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/CHLOE.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"emporio-armani": {
			KorName:       "엠포리오 아르마니",
			EngName:       "EMPORIO ARMANI",
			KeyName:       "EMPORIOARMANI",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/EMPORIOARMANI.png",
			Onpopular:     false,
			Description:   "컨템포러리 디자이너",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"fred-perry": {
			KorName:       "프레드페리",
			EngName:       "FRED PERRY",
			KeyName:       "FREDPERRY",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/FREDPERRY.png",
			Onpopular:     false,
			Description:   "컨템포러리 디자이너",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"fendi": {
			KorName:       "펜디",
			EngName:       "Fendi",
			KeyName:       "FENDI",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/FENDI.png",
			Onpopular:     false,
			Description:   "컨템포러리 디자이너",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"ganni": {
			KorName:       "가니",
			EngName:       "GANNI",
			KeyName:       "GANNI",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/GANNI.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"givenchy": {
			KorName:       "지방시",
			EngName:       "Givenchy",
			KeyName:       "GIVENCHY",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/GIVENCHY.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"golden-goose-deluxe-brand": {
			KorName:       "골든구스",
			EngName:       "GOLDEN GOOSE",
			KeyName:       "GOLDENGOOSE",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/GOLDENGOOSE.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"isabel-marant-etoile": {
			KorName:       "이자벨마랑 에뚜왈",
			EngName:       "Isabel Marant Etoile",
			KeyName:       "ISABELMARANTETOILE",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/ISABELMARANTETOILE.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"james-perse": {
			KorName:       "제임스펄스",
			EngName:       "James Perse",
			KeyName:       "JAMESPERSE",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/JAMESPERSE.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"jimmy-choo": {
			KorName:       "지미추",
			EngName:       "Jimmy Choo",
			KeyName:       "JIMMYCHOO",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/JIMMYCHOO.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"jacquemus": {
			KorName:       "자크뮈스",
			EngName:       "JACQUEMUS",
			KeyName:       "JACQUEMUS",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/JACQUEMUS.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"jw-anderson": {
			KorName:       "JW앤더슨",
			EngName:       "JW ANDERSON",
			KeyName:       "JWANDERSON",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/JWANDERSON.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"kenzo": {
			KorName:       "겐조",
			EngName:       "KENZO",
			KeyName:       "KENZO",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/KENZO.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"lacoste": {
			KorName:       "라코스테",
			EngName:       "LACOSTE",
			KeyName:       "LACOSTE",
			Description:   "트래디셔널 캐주얼",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/LACOSTE.png",
			Onpopular:     false,
			Created:       time.Now(),
			IsOpen:        true,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"lauren-by-ralph-lauren": {
			KorName:       "로렌 랄프 로렌",
			EngName:       "Lauren Ralph Lauren",
			KeyName:       "RLR",
			Description:   "트래디셔널 캐주얼",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/RLR.png",
			Onpopular:     false,
			Created:       time.Now(),
			IsOpen:        true,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"loewe": {
			KorName:       "로에베",
			EngName:       "LOEWE",
			KeyName:       "LOEWE",
			Description:   "컨템포러리 디자이너",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/LOEWE.png",
			Onpopular:     false,
			Created:       time.Now(),
			IsOpen:        false,
			IsHide:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"marcelo-burlon": {
			KorName:       "마르셀로 불론",
			EngName:       "Marcelo Burlon",
			KeyName:       "MARCELOBURLON",
			Description:   "컨템포러리 디자이너",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/MARCELOBURLON.png",
			Onpopular:     false,
			Created:       time.Now(),
			IsOpen:        false,
			IsHide:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"marni": {
			KorName:       "마르니",
			EngName:       "MARNI",
			KeyName:       "MARNI",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/MARNI.png",
			Onpopular:     false,
			Description:   "컨템포러리 디자이너",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"max-mara": {
			KorName:       "막스마라",
			EngName:       "MaxMara",
			KeyName:       "MAXMARA",
			Description:   "럭셔리",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/MAXMARA.png",
			Onpopular:     false,
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"max-mara-studio": {
			KorName:       "막스마라 스튜디오",
			EngName:       "MaxMara Studio",
			KeyName:       "MAXMARASTUDIO",
			Description:   "럭셔리",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/MAXMARASTUDIO.png",
			Onpopular:     false,
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"max-mara-weekend": {
			KorName:       "막스마라 위크엔드",
			EngName:       "MaxMara Weekend",
			KeyName:       "MAXMARAWEEKEND",
			Description:   "럭셔리",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/MAXMARAWEEKEND.png",
			Onpopular:     false,
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"miu-miu": {
			KorName:       "미우미우",
			EngName:       "MIU MIU",
			KeyName:       "MIUMIU",
			Description:   "럭셔리",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/MIUMIU.png",
			Onpopular:     false,
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"moschino": {
			KorName:       "모스키노",
			EngName:       "MOSCHINO",
			KeyName:       "MOSCHINO",
			Description:   "럭셔리",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/MOSCHINO.png",
			Onpopular:     false,
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"moncler": {
			KorName:       "몽클레르",
			EngName:       "Moncler",
			KeyName:       "MONCLER",
			Description:   "럭셔리",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/MONCLER.png",
			Onpopular:     false,
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"moose-knuckles": {
			KorName:       "무스너클",
			EngName:       "MOOSE KNUCKLES",
			KeyName:       "MOOSEKNUCKLES",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/MOOSEKNUCKLES.png",
			Onpopular:     false,
			Description:   "컨템포러리 디자이너",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"off-white": {
			KorName:       "오프화이트",
			EngName:       "Off White",
			KeyName:       "OFFWHITE",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/OFFWHITE.png",
			Onpopular:     false,
			Description:   "컨템포러리 디자이너",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"polo-ralph-lauren": {
			KorName:       "폴로 랄프로렌",
			EngName:       "Polo Ralph Lauren",
			KeyName:       "POLORALPHLAUREN",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/POLORALPHLAUREN.png",
			Onpopular:     false,
			Description:   "컨템포러리 디자이너",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"palm-angels": {
			KorName:       "팜 엔젤스",
			EngName:       "PALM ANGELS",
			KeyName:       "PALMANGELS",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/PALMANGELS.png",
			Onpopular:     false,
			Description:   "컨템포러리 디자이너",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"prada": {
			KorName:       "프라다",
			EngName:       "PRADA",
			KeyName:       "PRADA",
			Description:   "럭셔리",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/PRADA.png",
			Onpopular:     false,
			Created:       time.Now(),
			IsOpen:        false,
			IsHide:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"rick-owens-drkshdw": {
			KorName:       "릭 오웬스",
			EngName:       "Rick Owens",
			KeyName:       "RICKOWENS",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/RICKOWENS.png",
			Onpopular:     false,
			Description:   "컨템포러리 디자이너",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"stone-island": {
			KorName:       "스톤아일랜드",
			EngName:       "Stone Island",
			KeyName:       "STONEISLAND",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/STONEISLAND.png",
			Onpopular:     false,
			Description:   "컨템포러리 디자이너",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"stella-mccartney": {
			KorName:       "스텔라 맥카트니",
			EngName:       "Stella McCartney",
			KeyName:       "STELLAMCCARTNEY",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/STELLAMCCARTNEY.png",
			Onpopular:     false,
			Description:   "컨템포러리 디자이너",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"sportmax": {
			KorName:       "스포츠막스",
			EngName:       "SPORTMAX",
			KeyName:       "SPORTMAX",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/SPORTMAX.png",
			Onpopular:     false,
			Description:   "컨템포러리 디자이너",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"sporty-and-rich": {
			KorName:       "스포티 앤 리치",
			EngName:       "SPORTY AND RICH",
			KeyName:       "SPORTYANDRICH",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/SPORTYANDRICH.png",
			Onpopular:     false,
			Description:   "컨템포러리 디자이너",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"thom-browne": {
			KorName:       "톰 브라운",
			EngName:       "Thom Browne",
			KeyName:       "THOMBROWNE",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/THOMBROWNE.png",
			Onpopular:     false,
			Description:   "컨템포러리 디자이너",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"tommy-hilfiger": {
			KorName:       "타미 힐피거",
			EngName:       "Tommy Hilfiger",
			KeyName:       "TOMMYHILFIGERW",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/TOMMYHILFIGERW.png",
			Onpopular:     false,
			Description:   "트래디셔널 캐주얼",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: true,
			SizeGuide:     []domain.SizeGuideDAO{},
		},
		"tory-burch": {
			KorName:       "토리버치",
			EngName:       "Tory Burch",
			KeyName:       "TORYBURCH",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/TORYBURCH.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
		},
		"ten-c": {
			KorName:       "텐씨",
			EngName:       "TEN C",
			KeyName:       "TENC",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/TENC.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
		},
		"under-armour": {
			KorName:       "언더아머",
			EngName:       "underarmour",
			KeyName:       "UNDERARMOUR",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/UNDERARMOUR.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
		},
		"ugg": {
			KorName:       "어그",
			EngName:       "UGG",
			KeyName:       "UGG",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/UGG.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
		},
		"valentino": {
			KorName:       "발렌티노",
			EngName:       "Valentino",
			KeyName:       "VALENTINO",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/VALENTINO.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
		},
		"vivienne-westwood": {
			KorName:       "비비안 웨스트우드",
			EngName:       "ViVienne Westwood",
			KeyName:       "VIVIENNEWESTWOOD",
			LogoImgUrl:    "https://alloff.s3.ap-northeast-2.amazonaws.com/brands/VIVIENNEWESTWOOD.png",
			Onpopular:     false,
			Description:   "컨템포러리",
			Created:       time.Now(),
			IsOpen:        false,
			InMaintenance: false,
		},
	}

	for brandUrlName, brand := range brands {
		brDao, err := ioc.Repo.Brands.GetByKeyname(brand.KeyName)
		if err != nil && err == mongo.ErrNoDocuments {
			brDao, _ = ioc.Repo.Brands.Upsert(&brand)
		}

		source := domain.CrawlSourceDAO{
			BrandKeyname:         brDao.KeyName,
			BrandIdentifier:      brandUrlName,
			ProductType:          nil,
			CrawlUrl:             getCrawlUrl(brandUrlName),
			CrawlModuleName:      MODULE_NAME,
			IsSalesProducts:      true,
			IsForeignDelivery:    true,
			PriceMarginPolicy:    "CLAUDIEPIERLOT",
			DeliveryPrice:        0,
			EarliestDeliveryDays: 7,
			LatestDeliveryDays:   14,
			DeliveryDesc:         nil,
			RefundAvailable:      true,
			ChangeAvailable:      true,
			RefundFee:            100000,
			ChangeFee:            100000,
		}

		_, err = ioc.Repo.CrawlSources.Upsert(&source)
		if err != nil {
			log.Println(err)
		}
	}
}

func getCrawlUrl(brandUrlName string) string {
	brandKeys := map[string]string{
		"alexander-mcqueen":         "FLAN_CLEBRAALEXANDERMCQUEEN",
		"apc":                       "FLAN_CLEBRAAPC",
		"balenciaga":                "FLAN_APC",
		"balmain":                   "FLAN_CLEBRABALENCIAGA",
		"bash":                      "FLAN_CLEBRABASH",
		"burberry":                  "FLAN_CLEBRABURBERRY",
		"barbour-international":     "FLAN_CLEBRABARBOURINTERNATIONAL",
		"barbour":                   "FLAN_CLEBRABARBOUR",
		"coach":                     "FLAN_CLEBRACOACH",
		"champion":                  "FLAN_CLEBRACHAMPION",
		"calvin-klein-underwear":    "FLAN_CLEBRACALVINKLEINUNDERWEAR",
		"calvin-klein-performance":  "FLAN_CLEBRACALVINKLEINPERFORMANCE",
		"calvin-klein-jeans":        "FLAN_CLEBRACALVINKLEINJEANS",
		"canada-goose":              "FLAN_CLEBRACANADAGOOSE",
		"casablanca":                "FLAN_CLEBRACANADAGOOSE",
		"comme-des-garcons-play":    "FLAN_CLEBRACASABLANCA",
		"cp-company":                "FLAN_CLEBRACPCOMPANY",
		"chloe":                     "FLAN_CLEBRACHLOE",
		"emporio-armani":            "FLAN_CLEBRAEMPORIOARMANI",
		"fred-perry":                "FLAN_CLEBRAFREDPERRY",
		"fendi":                     "FLAN_CLEBRAFENDI",
		"ganni":                     "FLAN_CLEBRAGANNI",
		"givenchy":                  "FLAN_CLEBRAGIVENCHY",
		"golden-goose-deluxe-brand": "FLAN_CLEBRAGOLDENGOOSEDELUXEBRAND",
		"isabel-marant-etoile":      "FLAN_CLEBRAISABELMARANTETOILE",
		"james-perse":               "FLAN_CLEBRAJAMESPERSE",
		"jimmy-choo":                "FLAN_CLEBRAJIMMYCHOO",
		"jacquemus":                 "FLAN_CLEBRAJACQUEMUS",
		"jw-anderson":               "FLAN_CLEBRAJWANDERSON",
		"kenzo":                     "FLAN_CLEBRAKENZO",
		"lacoste":                   "FLAN_CLEBRALACOSTE",
		"lauren-by-ralph-lauren":    "FLAN_CLEBRALAURENBYRALPHLAUREN",
		"loewe":                     "FLAN_CLEBRALOEWE",
		"marcelo-burlon":            "FLAN_CLEBRAMARCELOBURLON",
		"marni":                     "FLAN_CLEBRAMARNI",
		"max-mara":                  "FLAN_CLEBRAMAXMARA",
		"max-mara-studio":           "FLAN_CLEBRAMAXMARASTUDIO",
		"max-mara-weekend":          "FLAN_CLEBRAMAXMARAWEEKEND",
		"miu-miu":                   "FLAN_CLEBRAMIUMIU",
		"moschino":                  "FLAN_CLEBRAMOSCHINO",
		"moncler":                   "FLAN_CLEBRAMONCLER",
		"moose-knuckles":            "FLAN_CLEBRAMOOSEKNUCKLES",
		"off-white":                 "FLAN_CLEBRAOFFWHITE",
		"polo-ralph-lauren":         "FLAN_CLEBRAPOLORALPHLAUREN",
		"palm-angels":               "FLAN_CLEBRAPALMANGELS",
		"prada":                     "FLAN_CLEBRAPRADA",
		"rick-owens-drkshdw":        "FLAN_CLEBRARICKOWENSDRKSHDW",
		"stone-island":              "FLAN_CLEBRASTONEISLAND",
		"stella-mccartney":          "FLAN_CLEBRASTELLAMCCARTNEY",
		"sportmax":                  "FLAN_CLEBRASPORTMAX",
		"sporty-and-rich":           "FLAN_CLEBRASPORTYANDRICH",
		"thom-browne":               "FLAN_CLEBRATHOMBROWNE",
		"tommy-hilfiger":            "FLAN_CLEBRATOMMYHILFIGER",
		"tory-burch":                "FLAN_CLEBRATORYBURCH",
		"ten-c":                     "FLAN_CLEBRATENC",
		"under-armour":              "FLAN_CLEBRAUNDERARMOUR",
		"ugg":                       "FLAN_CLEBRAUGG",
		"valentino":                 "FLAN_CLEBRAVALENTINO",
		"vivienne-westwood":         "FLAN_CLEBRAVIVIENNEWESTWOOD",
	}

	baseUrl := "https://www.flannels.com/api/productlist/v1/getforcategory"
	v := url.Values{}
	v.Set("page", "1")
	v.Set("productsPerPage", "10")
	v.Set("categoryId", brandKeys[brandUrlName])
	return baseUrl + "?" + v.Encode()
}
