FROM golang:1.16.4-buster AS builder

RUN mkdir /root/.ssh/
ADD ~/.ssh/id_rsa /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

WORKDIR /go/src/app
COPY . .

RUN go build -o apiServer ./cmd/apiServer/main.go
RUN go build -o grpcServer ./cmd/grpcServer/main.go

EXPOSE 80